import React, { useEffect, useState } from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import { useSession } from 'next-auth/client';
import { useRouter } from 'next/router';
import LinearProgress from '@mui/material/LinearProgress';

import { GetClassByCode } from '../../src/api/client';
import EnrollClass from '../../src/components/enrolClass';
import { IClass } from '../../src/type';

const Code: NextPage = () => {
	const [session, loading] = useSession();
	const router = useRouter();
	const [classData, setClassData] = useState<IClass>();
	const { isReady } = router;

	useEffect(() => {
		if (router.isReady) {
			const { code } = router.query;
			GetClassByCode(code as string).then((data) => {
				setClassData(data);
			});
		}
	}, [isReady]);

	return loading && !classData ? (
		<LinearProgress color='secondary' />
	) : (
		<React.Fragment>
			<Head>
				<title>Fit Class</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<EnrollClass isAuth={!!session} classData={classData as IClass} />
		</React.Fragment>
	);
};

export default Code;
