import React, { useState } from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import useRouter from 'next/router';
import TextField from '@mui/material/TextField';
import Typography from '@mui/material/Typography';

import { StyledContainer } from '../../src/components/enrollClass/style';
import RoundedButton from '../../src/components/UI/RoundedButton';

const Enroll: NextPage = () => {
  const router = useRouter;
  const [code, setCode] = useState('');

  const handleChangeCode = ({ target }: React.ChangeEvent<HTMLInputElement>) => {
    setCode(target.value);
  };

  const handleSubmit = async () => {
    const url = `/enroll/${code}`;
    await router.push(url);
  };

  return (
    <React.Fragment>
      <Head>
        <title>Fit Class - Tham gia lớp học</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <StyledContainer>
        <Typography variant='h4'>Ghi danh vào lớp học</Typography>
        <TextField margin='normal' label='Mã lớp' autoFocus value={code} onChange={handleChangeCode} placeholder='Nhập mã lớp học' />
        <RoundedButton variant='contained' onClick={handleSubmit}>
          Tham gia
        </RoundedButton>
      </StyledContainer>
    </React.Fragment>
  );
};

export default Enroll;
