import React, { useContext, useEffect } from 'react';
import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';
import { getSession } from 'next-auth/client';
import Box from '@mui/material/Box';
import ClassIcon from '@mui/icons-material/Class';

import NavProvider from '../../../src/store/detailNav';
import InviteStudentPopup from '../../../src/components/inviteStudentPopup';
import Header from '../../../src/components/header';
import ClassGrade from '../../../src/components/classGrade';
import { IClass } from '../../../src/type';
import { GetClass } from '../../../src/api/server';
import Navigation from '../../../src/components/navigation';
import { ClassContext } from '../../../src/store/class';

interface ClassPageProps {
	classData: IClass;
}

const GradePage: NextPage<ClassPageProps> = ({ classData }: ClassPageProps) => {
	const { StoreCurrentClass } = useContext(ClassContext);

	useEffect(() => {
		StoreCurrentClass(classData);
	}, []);

	return (
		<NavProvider>
			<Head>
				<title>Fit Class - {classData.name}</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Box sx={{ display: 'flex' }}>
				<Navigation classDetail />
				<Box width='100%'>
					<Header
						title={classData.code.toUpperCase()}
						icon={<ClassIcon />}
						link={`/class/${classData.code}`}
						isAuth
					/>
					<ClassGrade />
				</Box>
			</Box>
		</NavProvider>
	);
};

export const getServerSideProps: GetServerSideProps = async (context) => {
	const session = await getSession(context);
	const code = context.params?.code as string;
	if (session) {
		const classData = await GetClass(code, session?.accessToken as string);

		if (classData) {
			return {
				props: {
					classData
				}
			};
		}
		return {
			redirect: {
				destination: '/class',
				statusCode: 302
			}
		};
	}
	return {
		redirect: {
			destination: '/signin',
			statusCode: 302
		}
	};
};

export default GradePage;
