import React from 'react';
import Head from 'next/head';
import { getSession } from 'next-auth/client';
import ClassIcon from '@mui/icons-material/Class';

import { wrapper } from '../../../src/reducers';
import { Page } from '../../../src/type/page';
import { ClassActions } from '../../../src/reducers/class';
import ClassGrade from '../../../src/components/classGrade';
import { IClass } from '../../../src/type';
import { GetClass } from '../../../src/api/server';
import ClassLayout from '../../../src/components/layout/class';

interface ClassPageProps {
	classData: IClass;
}

const GradePage: Page<ClassPageProps> = ({ classData }: ClassPageProps) => {
	return (
		<React.Fragment>
			<Head>
				<title>Fit Class - {classData.name}</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<ClassGrade />
		</React.Fragment>
	);
};

export const getServerSideProps = wrapper.getServerSideProps((store) => async (context) => {
	const session = await getSession(context);
	const code = context.params?.code as string;
	if (session) {
		const classData = await GetClass(code, session?.accessToken as string);
		store.dispatch(ClassActions.enterClass(classData));

		if (classData) {
			return {
				props: {
					classData
				}
			};
		}
		return {
			redirect: {
				destination: '/class',
				statusCode: 302
			}
		};
	}
	return {
		redirect: {
			destination: '/signin',
			statusCode: 302
		}
	};
});

GradePage.getLayout = (page: React.ReactElement) => {
	return (
		<ClassLayout icon={<ClassIcon />} title={page.props.classData.code}>
			{page}
		</ClassLayout>
	);
};

export default GradePage;
