import React from 'react';
import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';
import { Session } from 'next-auth';
import { getSession } from 'next-auth/client';

import ClassIcon from '@mui/icons-material/Class';

import NavProvider from '../../src/store/detailNav';
import Header from '../../src/components/header';
import NavTab from '../../src/components/navTab';
import ClassContent from '../../src/components/classContent';
import { IClass } from '../../src/type';
import { GetClass } from '../../src/api/server';

interface ClassPageProps {
	classData: IClass;
	session: Session;
}

const ClassPage: NextPage<ClassPageProps> = ({ classData, session }: ClassPageProps) => {
	return (
		<NavProvider>
			<Head>
				<title>{classData.name}</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header title='Fit classes' icon={<ClassIcon />} middleAction={<NavTab />} session={session} />
			<ClassContent classData={classData} />
		</NavProvider>
	);
};

export const getServerSideProps: GetServerSideProps = async (context) => {
	const session = await getSession(context);
	const code = context.params?.code as string;
	if (session) {
		const classData = await GetClass(code, session?.accessToken as string);

		return {
			props: {
				classData,
				session
			}
		};
	}
	return {
		redirect: {
			destination: '/signin',
			statusCode: 302
		}
	};
};

export default ClassPage;
