import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

import ClassIcon from '@mui/icons-material/Class';

import Classes from '../src/components/classes';
import Header from '../src/components/header';
import AddClassModal from '../src/components/addClassModal';
import { IClass } from '../src/type';

const DUMMY: IClass[] = [
	{
		id: 1,
		name: 'PTUDW',
		identity: 'GTA32',
		thematic: 'abc'
	}
	{
		id: 1,
		name: 'PTUDW',
		identity: 'GTA32',
		thematic: 'abc'
	}
	{
		id: 1,
		name: 'PTUDW',
		identity: 'GTA32',
		thematic: 'abc'
	}
];

const Home: NextPage = () => {
	return (
		<React.Fragment>
			<Head>
				<title>Classes</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header title='Fit classes' icon={<ClassIcon />} rightAction={<AddClassModal />} />
			<Classes classes={DUMMY} />
		</React.Fragment>
	);
};

export default Home;
