import React, { useEffect } from 'react';
import { NextPage } from 'next';
import { useRouter } from 'next/router';
import { useSession } from 'next-auth/client';
import Head from 'next/head';

const Index: NextPage = () => {
	const [session] = useSession();
	const router = useRouter();

	useEffect(() => {
		if (session) {
			router.push('/class');
		} else {
			router.push('/signin');
		}
	}, []);

	return (
		<React.Fragment>
			<Head>
				<title>Fit Class</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
		</React.Fragment>
	);
};

export default Index;
