import React, { useEffect } from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useSession } from 'next-auth/client';
import LockOpenRounded from '@mui/icons-material/LockOpenRounded';
import LinearProgress from '@mui/material/LinearProgress';

import Header from '../src/components/header';
import SignUpForm from '../src/components/auth/signUpForm';

const SignUp: NextPage = () => {
	const [session, loading] = useSession();
	const router = useRouter();

	/* Handle for google sign in and already sign in */
	useEffect(() => {
		if (!loading && session) {
			const redirectUrl = router.query.redirect as string;
			if (redirectUrl) {
				router.push(redirectUrl);
			} else {
				router.push('/class');
			}
		}
	}, [session, loading]);

	return loading ? (
		<LinearProgress color='secondary' />
	) : (
		<React.Fragment>
			<Head>
				<title>Đăng Ký</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header title='Đăng ký' icon={<LockOpenRounded />} />
			<SignUpForm />
		</React.Fragment>
	);
};

export default SignUp;
