import React from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import LockOpenRounded from '@mui/icons-material/LockOpenRounded';

import Header from '../../src/components/header';
import SignInForm from '../../src/components/auth/signInForm';

const SignIn: NextPage = () => {
	return (
		<React.Fragment>
			<Head>
				<title>Đăng Nhập</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header title='Fit class' icon={<LockOpenRounded />} />
			<SignInForm />
		</React.Fragment>
	);
};

export default SignIn;
