import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { GetServerSideProps } from 'next';
import { getSession } from 'next-auth/client';

import ClassIcon from '@mui/icons-material/Class';

import NavProvider from '../../../src/store/detailNav';
import Header from '../../../src/components/header';
import NavTab from '../../../src/components/navTab';
import ClassContent from '../../../src/components/classContent';

const Home: NextPage = () => {
	return (
		<NavProvider>
			<Head>
				<title>Classes</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header title='Fit classes' icon={<ClassIcon />} middleAction={<NavTab />} />
			<ClassContent />
		</NavProvider>
	);
};

export const getServerSideProps: GetServerSideProps = async (context) => {
	const session = await getSession(context);
	if (session) {
		return {
			props: {}
		};
	}
	return {
		redirect: {
			destination: '/signin',
			statusCode: 302
		}
	};
};

export default Home;
