import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

import ClassIcon from '@mui/icons-material/Class';

import NavProvider from '../../../src/store/detailNav';
import Header from '../../../src/components/header';
import NavTab from '../../../src/components/navTab';
import ClassContent from '../../../src/components/classContent';

const Home: NextPage = () => {
	return (
		<NavProvider>
			<Head>
				<title>Classes</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header title='Fit classes' icon={<ClassIcon />} middleAction={<NavTab />} />
			<ClassContent />
		</NavProvider>
	);
};

export default Home;
